package com.gabriel0liv.partialreload.joint;

public enum TagRecipeTransactionEventType {
    STATUS_CHANGED, FAILURE, SAFE_POINT_REACHED, PREFLIGHT_PASSED, REGISTRY_SCOPE_DERIVED,
    CANDIDATE_BUILT, CANDIDATE_BINDINGS_BUILT, CANDIDATE_RECIPES_BUILT,
    PREVIOUS_GENERATION_CAPTURED, TAG_BIND_STARTED, TAG_BOUND,
    TAG_REGISTRY_REPLACEMENT_STARTED, TAG_REGISTRY_REPLACED_EXACT,
    RECIPES_PUBLISHED, RECIPE_PUBLICATION_STARTED,
    INGREDIENTS_INVALIDATED, INGREDIENT_INVALIDATION_STARTED,
    TAGS_EVENT_DISPATCHED, TAGS_EVENT_DISPATCH_STARTED,
    DEFERRED_PLAYERS_CAPTURED, DEFERRED_MENU_CLOSE_STARTED, DEFERRED_MENUS_CLOSED,
    DEFERRED_CLIENTS_MARKED_STALE, VERIFICATION_STARTED, VERIFICATION_PASSED,
    ROLLBACK_STARTED, ROLLBACK_RECIPES_RESTORED,
    ROLLBACK_TAG_REGISTRY_REPLACEMENT_STARTED, ROLLBACK_TAG_RESTORED,
    ROLLBACK_INGREDIENT_INVALIDATION_STARTED, ROLLBACK_INGREDIENTS_INVALIDATED,
    ROLLBACK_TAGS_EVENT_DISPATCH_STARTED, ROLLBACK_TAGS_EVENT_DISPATCHED,
    ROLLBACK_VERIFICATION_STARTED, ROLLBACK_VERIFICATION_PASSED, DEGRADED
}
