package com.gabriel0liv.partialreload.joint;

public enum TagRecipeTransactionEventType {
    STATUS_CHANGED, FAILURE, SAFE_POINT_REACHED, PREFLIGHT_PASSED, REGISTRY_SCOPE_DERIVED,
    CANDIDATE_BUILT, TAG_BIND_STARTED, TAG_BOUND, TAG_REGISTRY_REPLACED_EXACT, RECIPES_PUBLISHED, INGREDIENTS_INVALIDATED,
    TAGS_EVENT_DISPATCHED, VERIFICATION_PASSED, ROLLBACK_STARTED, ROLLBACK_RECIPES_RESTORED,
    ROLLBACK_TAG_RESTORED, ROLLBACK_INGREDIENTS_INVALIDATED, ROLLBACK_TAGS_EVENT_DISPATCHED,
    ROLLBACK_VERIFICATION_PASSED, DEGRADED
}
