package com.gabriel0liv.partialreload.joint;

public enum TagRecipeFaultPoint {
    BEFORE_FIRST_TAG_BIND, AFTER_FIRST_TAG_BIND, BEFORE_SECOND_TAG_BIND,
    AFTER_ALL_TAG_BINDS, BEFORE_RECIPE_PUBLICATION, AFTER_RECIPE_PUBLICATION,
    AFTER_INGREDIENT_INVALIDATION, AFTER_TAGS_UPDATED_EVENT, BEFORE_VERIFICATION,
    DURING_ROLLBACK
}
