package com.gabriel0liv.partialreload.gametest;
import com.gabriel0liv.partialreload.PartialReloadMod;
import com.gabriel0liv.partialreload.core.*;
import com.gabriel0liv.partialreload.joint.*;import com.gabriel0liv.partialreload.resource.ResourceSnapshot;
import net.minecraft.core.*;import net.minecraft.core.registries.BuiltInRegistries;import net.minecraft.core.registries.Registries;import net.minecraft.gametest.framework.GameTestHelper;import net.minecraft.resources.*;import net.minecraft.server.MinecraftServer;import net.minecraft.tags.TagKey;import net.minecraft.world.item.Item;import net.minecraftforge.fml.ModList;import java.util.*;
final class TagRecipeGameTestFixture implements AutoCloseable {
 private final GameTestHelper helper;private final MinecraftServer server;private final PartialReloadService service;private final TagRecipeGameTestState originalState;private final ActiveTagRecipeGeneration originalPhysical;private final int accessId,itemId,recipeId;private TagRecipeGameTestPreparation.PreparedFixtureGeneration a,b;private boolean closed;
 static TagRecipeGameTestFixture create(GameTestHelper h){MinecraftServer s=h.getLevel().getServer();PartialReloadMod m=ModList.get().getModObjectById(PartialReloadMod.MOD_ID).filter(PartialReloadMod.class::isInstance).map(PartialReloadMod.class::cast).orElseThrow();return new TagRecipeGameTestFixture(h,s,m.service());}
 private TagRecipeGameTestFixture(GameTestHelper h,MinecraftServer s,PartialReloadService svc){helper=h;server=s;service=svc;if(!TagRecipeFaultInjection.pending().isEmpty())throw new IllegalStateException("fault queue not empty");originalState=svc.captureTagRecipeGameTestState();accessId=System.identityHashCode(s.registryAccess());itemId=System.identityHashCode(s.registryAccess().registryOrThrow(Registries.ITEM));recipeId=System.identityHashCode(s.getRecipeManager());a=TagRecipeGameTestPreparation.prepare(s,resources(false),null);originalPhysical=svc.captureTagRecipeGenerationForGameTest(s,a.artifact());}
 PartialReloadService service(){return service;}MinecraftServer server(){return server;}
 void installGenerationA(){if(a==null)throw new IllegalStateException("not created");service.installTagRecipeGameTestReadyState(new ResourceSnapshot(java.time.Instant.now(),Map.of()),a.snapshot(),a.changeSet(),a.artifact(),(s,e)->e==a.snapshot());var tx=service.requestTagRecipeCommit(server,"gametest-setup-a");service.processTagRecipeSafePoint(server);if(tx.status()!=TagRecipeTransactionStatus.SUCCESS)throw new AssertionError("setup A failed: "+tx.status());}
 void prepareGenerationB(){b=TagRecipeGameTestPreparation.prepare(server,resources(true),a.snapshot());service.installTagRecipeGameTestReadyState(a.snapshot(),b.snapshot(),b.changeSet(),b.artifact(),(s,e)->e==b.snapshot());}
 void assertGenerationA(){assertItemTag("item_joint","minecraft:stone");assertRecipe(1);}
 void assertGenerationB(){assertItemTag("item_joint","minecraft:dirt");assertRecipe(2);}
 @SuppressWarnings({"rawtypes", "unchecked"}) private void assertRecipe(int expectedCount){var recipe=server.getRecipeManager().byKey(id("acceptance")).orElseThrow(()->new AssertionError("fixture recipe missing"));var result=recipe.getResultItem(server.registryAccess());if(!result.is(net.minecraft.world.item.Items.TORCH)||result.getCount()!=expectedCount)throw new AssertionError("recipe count/result mismatch");if(recipe.getSerializer()!=net.minecraft.world.item.crafting.RecipeSerializer.SHAPELESS_RECIPE||recipe.getType()!=net.minecraft.world.item.crafting.RecipeType.CRAFTING)throw new AssertionError("recipe type/serializer mismatch");long occurrences=0;for(Object candidate:((net.minecraft.world.item.crafting.RecipeManager)server.getRecipeManager()).getAllRecipesFor((net.minecraft.world.item.crafting.RecipeType)recipe.getType()))if(((net.minecraft.world.item.crafting.Recipe<?>)candidate).getId().equals(id("acceptance")))occurrences++;if(occurrences!=1)throw new AssertionError("recipe index occurrence="+occurrences);}
 void assertCleanup(){if(System.identityHashCode(server.registryAccess())!=accessId||System.identityHashCode(server.registryAccess().registryOrThrow(Registries.ITEM))!=itemId||System.identityHashCode(server.getRecipeManager())!=recipeId)throw new AssertionError("identity changed");if(service.tagRecipeTransaction()!=originalState.tagRecipeTransaction())throw new AssertionError("transaction not restored");}
 void assertItemTag(String name,String expected){TagKey<Item> key=TagKey.create(Registries.ITEM,id(name));var set=server.registryAccess().registryOrThrow(Registries.ITEM).getTag(key).orElseThrow();var value=set.stream().findFirst().orElseThrow().value();if(!Objects.equals(BuiltInRegistries.ITEM.getKey(value),ResourceLocation.parse(expected)))throw new AssertionError("tag "+name);}
 private Map<ResourceLocation,String> resources(boolean b){String v=b?"minecraft:dirt":"minecraft:stone";String recipe="{\"type\":\"minecraft:crafting_shapeless\",\"ingredients\":[{\"tag\":\"partialreload:gametest_tx/item_joint\"}],\"result\":{\"item\":\"minecraft:torch\",\"count\":"+(b?2:1)+"}}";Map<ResourceLocation,String>m=new LinkedHashMap<>();m.put(loc("tags/items/gametest_tx/item_joint.json"),tag(v));m.put(loc("recipes/gametest_tx/acceptance.json"),recipe);return m;}
 private String tag(String v){return "{\"replace\":true,\"values\":[\""+v+"\"]}";}private ResourceLocation loc(String p){return ResourceLocation.fromNamespaceAndPath("partialreload",p);}private ResourceLocation id(String n){return ResourceLocation.fromNamespaceAndPath("partialreload","gametest_tx/"+n);}
 @Override public void close(){if(closed)return;try{service.releaseTagRecipeSafePoint();service.resetConnectedPlayerProbe();TagRecipeFaultInjection.clear();service.restoreTagRecipeGenerationForGameTest(server,originalPhysical);service.restoreTagRecipeGameTestState(originalState);}finally{closed=true;}}
}
