package com.gabriel0liv.partialreload.function;

public enum TransactionEventType {
    REQUESTED,
    VALIDATED,
    QUEUED,
    SAFE_POINT_REACHED,
    PREVIOUS_GENERATION_CAPTURED,
    CANDIDATE_BUILT,
    LIBRARY_SWAPPED,
    LOAD_SUPPRESSED,
    TICK_SET_UPDATED,
    VERIFICATION_STARTED,
    VERIFICATION_PASSED,
    BASELINE_PROMOTED,
    SUCCESS,
    ROLLBACK_STARTED,
    ROLLBACK_COMPLETED,
    FAILED,
    DEGRADED
}
