package com.gabriel0liv.partialreload.advancement;
import java.time.Instant;import java.util.*;
public final class AdvancementCommitTransaction {
 private final UUID transactionId,preparationId;private final Instant createdAt;private final String requester;private final int managerIdentity;private final ActiveAdvancementGeneration expectedActiveGeneration;private final AdvancementDependencySnapshot expectedDependencies;
 private AdvancementTransactionStatus status=AdvancementTransactionStatus.PREPARING;private ActiveAdvancementGeneration previousGeneration,candidateGeneration;private List<PlayerAdvancementStateSnapshot> playerSnapshots=List.of();private final Set<UUID> playersRebound=new LinkedHashSet<>();private int clientsSynced;private boolean managerPublished,rollbackPerformed;private String failure;
 public AdvancementCommitTransaction(UUID transactionId,UUID preparationId,Instant createdAt,String requester,int managerIdentity,ActiveAdvancementGeneration expectedActiveGeneration,AdvancementDependencySnapshot expectedDependencies){this.transactionId=transactionId;this.preparationId=preparationId;this.createdAt=createdAt;this.requester=requester;this.managerIdentity=managerIdentity;this.expectedActiveGeneration=expectedActiveGeneration;this.expectedDependencies=expectedDependencies;}
 public UUID transactionId(){return transactionId;}public UUID preparationId(){return preparationId;}public Instant createdAt(){return createdAt;}public String requester(){return requester;}public int managerIdentity(){return managerIdentity;}public ActiveAdvancementGeneration expectedActiveGeneration(){return expectedActiveGeneration;}public AdvancementDependencySnapshot expectedDependencies(){return expectedDependencies;}
 public AdvancementTransactionStatus status(){return status;}public void status(AdvancementTransactionStatus v){status=v;}public ActiveAdvancementGeneration previousGeneration(){return previousGeneration;}public void previousGeneration(ActiveAdvancementGeneration v){previousGeneration=v;}public ActiveAdvancementGeneration candidateGeneration(){return candidateGeneration;}public void candidateGeneration(ActiveAdvancementGeneration v){candidateGeneration=v;}public List<PlayerAdvancementStateSnapshot> playerSnapshots(){return playerSnapshots;}public void playerSnapshots(List<PlayerAdvancementStateSnapshot> v){playerSnapshots=List.copyOf(v);}public Set<UUID> playersRebound(){return Set.copyOf(playersRebound);}public void playerRebound(UUID id){playersRebound.add(id);}public int clientsSynced(){return clientsSynced;}public void clientSynced(){clientsSynced++;}public boolean managerPublished(){return managerPublished;}public void managerPublished(boolean v){managerPublished=v;}public boolean rollbackPerformed(){return rollbackPerformed;}public void rollbackPerformed(boolean v){rollbackPerformed=v;}public String failure(){return failure;}public void failure(String v){failure=v;}
}
